blowhorn/apps/urls.py
from django.conf.urls import url, include


urlpatterns = [
            url(r'^customers/',  include('blowhorn.apps.customer_app.urls')),
            url(r'^drivers/', include('blowhorn.apps.driver_app.urls')),
            url(r'^operations/', include('blowhorn.apps.operation_app.urls')),
            url(r'^kiosk/', include('blowhorn.apps.kiosk.urls')),
            url(r'^integrations/', include('blowhorn.apps.integrations.urls')),
        ]

blowhorn/urls.py
from django.conf.urls import url
from blowhorn.common.firebase_token import FirebaseToken
from django.urls import include, path

urlpatterns = [
        url(r'^firebasetoken/(?P<token_id>[\w-]+)$', FirebaseToken.as_view(), name='firebase-token'),
        url(r'^', include('blowhorn.address.urls')),
        url(r'^', include('blowhorn.apps.urls')),
        url(r'^', include('blowhorn.changelog.app')),
        url(r'^', include('blowhorn.company.urls')),
        url(r'^', include('blowhorn.contract.urls')),
        url(r'^', include('blowhorn.coupon.urls')),
        url(r'^', include('blowhorn.customer.urls')),
        url(r'^', include('blowhorn.driver.urls')),
        url(r'^', include('blowhorn.exotel.urls')),
        url(r'^', include('blowhorn.livetracking.urls')),
        url(r'^', include('blowhorn.mitra.urls')),
        url(r'^', include('blowhorn.order.urls')),
        url(r'^', include('blowhorn.payment.urls')),
        url(r'^', include('blowhorn.report.urls')),
        url(r'^', include('blowhorn.route_optimiser.urls')),
        url(r'^', include('blowhorn.trip.urls')),
        url(r'^', include('blowhorn.mitra.urls')),
        url(r'^', include('blowhorn.wms.urls')),
        url(r'^', include('blowhorn.shopify.urls')),
        url(r'^', include('blowhorn.integration_apps.urls')),
        url(r'^', include('blowhorn.vehicle.urls')),
        ]

blowhorn/wms/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^wms/v1/', include('blowhorn.wms.v1.app')),
    url(r'^wms/v2/', include('blowhorn.wms.v2.app')),
]

config/urls.py
import django
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.contrib.auth import views as auth_views
from django.apps import apps
from two_factor import urls as two_factor_url
# from blowhorn.app import application as api
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token

# from blowhorn.legacy.app import application as legacy_api
from graphene_django.views import GraphQLView
from organizations.backends import invitation_backend
from django.views.i18n import JavaScriptCatalog
from django.contrib.flatpages import views
# from blowhorn.app import Blowhorn


# from blowhorn.oscar.core.loading import get_class

# bh_app = get_class('app', 'Blowhorn')

js_info_dict = {
    'packages': ('recurrence', ),
}

urlpatterns = [
    url(r'', include('website.urls')),
    url(r'', include('blowhorn.livetracking.urls')),
    url(r'', include('blowhorn.changelog.urls')),
    # Django Admin, use {% url 'admin:index' %}
    # url(r'^account/login/$', auth_views.login, {'template_name': 'registration/login.html'}),
    url(r'^account/login/$', auth_views.LoginView.as_view(template_name='registration/login.html')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    #    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    #    url(r'^admin', include(admin.site.urls)),
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),

    # User management
    url(r'^users/', include(('blowhorn.users.urls', 'users'), namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # JWT Authentication
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-refresh/', refresh_jwt_token),
    url(r'^api-token-verify/', verify_jwt_token),

    # SQL Explorer
    #url(r'^explorer/', include('explorer.urls')),

    # Your stuff: custom urls includes go here
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # url(r'', two_factor_url.url),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view, js_info_dict),
    # url(r'', include(apps.get_app_config('oscar').urls[0])),
    url(r'^api/', include('blowhorn.urls')),
    # url(r'', legacy_api.urls),
    url(r'^organization/', include('organizations.urls')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^invitations/', include(invitation_backend().get_urls())),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

handler404 = 'website.views.custom_404'

blowhorn/address/models.py
# System and Django imports
from django.core.validators import RegexValidator
from django.contrib.gis.db import models
from django.db.models import Manager as GeoManager
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from django.contrib.postgres.fields import ArrayField
import datetime as dtime

# 3rd party libraries
from blowhorn.oscar.core.loading import get_model
from blowhorn.oscar.apps.address.abstract_models import (AbstractUserAddress,
                                                         AbstractShippingAddress, AbstractCountry)
from blowhorn.oscar.models.fields import AutoSlugField
from auditlog.registry import auditlog
from auditlog.models import AuditlogHistoryField
from phonenumber_field.modelfields import PhoneNumberField

# blowhorn modules
from blowhorn.common.models import BaseModel
from blowhorn.customer.models import Customer
from blowhorn.users.models import User
from datetime import datetime
from blowhorn.address.constants import SMS_PROVIDERS, CITY_TIERS
from blowhorn.common.middleware import current_request


# Client = get_model('wms', 'Client')


class Country(AbstractCountry):
    pass

class UserAddressManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related('country')


class UserAddress(AbstractUserAddress):
    geopoint = models.PointField(null=True, blank=True, srid=4326, help_text=_(
        "Represented as (longitude, latitude)"))
    identifier = models.CharField(_("Address Identifier"), null=True,
                                  blank=True, max_length=255,
                                  help_text=_("Address Identifier"))
    objects = UserAddressManager()

    def save(self, *args, **kwargs):
        super(UserAddress, self).save(*args, **kwargs)


class GenericAddressManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related('country')


class GenericAddress(AbstractShippingAddress):
    geopoint = models.PointField(null=True, blank=True, srid=4326, help_text=_(
        "Represented as (longitude, latitude)"))
    identifier = models.CharField(_("Address Identifier"), null=True,
                                  blank=True, max_length=255,
                                  help_text=_("Address Identifier"))
    objects = GenericAddressManager()


class CityManager(GeoManager):
    def get_queryset(self):
        return super().get_queryset().select_related('address')

    def get_cities_for_managerial_user(self, user):
        return self.get_queryset().filter(managers=user)

    def get_cities_for_given_user(self, user):
        qs = super().get_queryset()
        query = Q(managers=user) | Q(operation_managers=user)
        return qs.filter(query).distinct()

    def get_cities_list(self):
        """
        :return: list of cities with dict containing pk, name
        """
        city_qs = super().get_queryset().only('pk', 'name').order_by('name')
        return [{'id': city.pk, 'name': city.name} for city in city_qs]

    def get_super_queryset(self):
        return super().get_queryset()


class City(models.Model):
    """
    City model
    """
    import datetime
    history = AuditlogHistoryField()
    name = models.CharField(
        _("City Name"), max_length=255, blank=False,
        unique=True)

    tier = models.CharField(
        _('Tier'), max_length=50, null=True, blank=True, choices=CITY_TIERS
    )
    # Help search
    slug = AutoSlugField(populate_from='name', max_length=255)

    # This field is deprecated
    coverage = models.PolygonField(
        help_text=_("The coverage area for the city"), null=True, blank=True)

    coverage_pickup = models.PolygonField(
        help_text=_("The coverage area for pickup location"), null=True,
        blank=True)

    coverage_dropoff = models.PolygonField(
        help_text=_("The coverage area for dropoff location"), null=True,
        blank=True)

    shipment_coverage = models.PolygonField(
        help_text=_("The coverage area for shipment orders"), null=True,
        blank=True)

    contact = PhoneNumberField(
        _("Phone number/Mobile Number"), null=True, blank=True,
        help_text=_("Contact number of city branch office"))

    supply_contact_number = PhoneNumberField(
        _("Supply Contact Number"), null=True, blank=True,
        help_text=_("Supply contact number of city branch office"))

    default_vehicle_class = models.ForeignKey('vehicle.VehicleClass',
                                              null=True, blank=True, on_delete=models.CASCADE,
                                              help_text=_(
                                                  "Shown as default selected vehicle class for c2c bookings in app"))

    default_contract = models.ForeignKey('contract.Contract',
                                         null=True, blank=True, related_name='city_contract', on_delete=models.CASCADE,
                                         help_text=_("Shown as default selected rate card for c2c bookings in app"))

    loading_mins = models.IntegerField(
        _('Loading time in mins'), blank=False, null=False, default=25,
        help_text=_("Loading time used in Fare estimation for c2c bookings in app"))

    unloading_mins = models.IntegerField(
        _('Unloading time in mins'), blank=False, null=False, default=20,
        help_text=_("Unloading time used in Fare estimation for c2c bookings in app"))

    start_time = models.TimeField(help_text=_("Booking acceptance start time "
                                              "for the city"), null=True, blank=True)
    end_time = models.TimeField(help_text=_("Booking acceptance end time for "
                                            "the city"), null=True, blank=True)
    address = models.OneToOneField(GenericAddress, null=True, blank=True,
                                   related_name='city_branch_address',
                                   on_delete=models.CASCADE)
    managers = models.ManyToManyField(User, related_name="city_managers",
                                      limit_choices_to={'is_staff': True})
    finance_users = models.ManyToManyField(User, related_name="finance_users",
                                           limit_choices_to={'is_staff': True})
    operation_managers = models.ManyToManyField(
        User, related_name="operation_managers", blank=True,
        limit_choices_to={'is_staff': True})

    sales_representatives = models.ManyToManyField(
        User, related_name="sales_representatives", blank=True,
        limit_choices_to={'is_staff': True})

    supply_users = models.ManyToManyField(
        User, related_name="supply_users", blank=True,
        limit_choices_to={'is_staff': True})

    autodispatch_driver = models.ManyToManyField(
        'driver.Driver', related_name="autodispatch_drivers", blank=True)

    process_associates = models.ManyToManyField(
        User, related_name="process_associates", blank=True,
        limit_choices_to={'is_staff': True})

    head_office = models.ForeignKey('company.Office', null=True,
                                    on_delete=models.CASCADE)

    future_booking_days = models.IntegerField(
        _('Booking Days Allowed'), default=14,
        help_text=_("Number of Days booking is allowed from today "))

    night_hours_start_time = models.TimeField(help_text=_("Night Hours start time "), default=datetime.time(18, 00))

    night_hours_end_time = models.TimeField(help_text=_("Night Hours end time "), default=datetime.time(6, 00))

    # sms_provider = models.CharField(_('SMS Provider'), max_length=10, null=True, blank=True, choices=SMS_PROVIDERS)

    objects = CityManager()

    def __str__(self):
        return self.name

    def clean(self):
        if not self.coverage_pickup and self.coverage_dropoff:
            self.coverage_pickup = self.coverage_dropoff
            self.shipment_coverage = self.coverage_dropoff

        elif not self.coverage_dropoff and self.coverage_pickup:
            self.coverage_dropoff = self.coverage_pickup
            self.shipment_coverage = self.coverage_pickup

    @property
    def coverage_pickup_centroid(self):
        """
        Returns the centroid from coordinates defined in coverage.
        """
        return self.coverage_pickup.centroid

    @property
    def shipment_coverage_centroid(self):
        """
        Returns the centroid from coordinates defined in coverage.
        """
        return self.shipment_coverage.centroid

    @property
    def coverage_dropoff_centroid(self):
        """
        Returns the centroid from coordinates defined in coverage.
        """
        return self.coverage_dropoff.centroid

    class Meta:
        verbose_name = _("City")
        verbose_name_plural = _("Cities")

    @property
    def service_state(self):
        """
        Returns the State where Blowhorn services - has to be present in
        company.
        """

        return self.head_office.state if self.head_office else None


auditlog.register(City)


class State(models.Model):
    """
    Indian State model
    """
    name = models.CharField(
        _("State Name"), max_length=255, blank=False, unique=True)

    code = models.CharField(
        _("State Code"), max_length=2, blank=False)

    gst_code = models.CharField(
        _("GST State Code"), max_length=2, blank=False)

    cities = models.ManyToManyField(City, blank=True)

    country = models.ForeignKey('address.Country', on_delete=models.PROTECT,
                                null=True, blank=False)

    # Help search
    slug = AutoSlugField(populate_from='name', max_length=255)

    rcm_message = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("State")
        verbose_name_plural = _("States")


class WarehouseManager(GeoManager):
    def get_queryset(self):
        return super().get_queryset()

blowhorn/apps/customer_app/v1/models.py
from django.db import models

# Create your models here.

blowhorn/apps/kiosk/models.py
from django.db import models

# Create your models here.

blowhorn/apps/operation_app/v1/models.py
from django.db import models

# Create your models here.

blowhorn/apps/operation_app/v2/models.py
from django.db import models

# Create your models here.

blowhorn/apps/operation_app/v3/models.py
from django.db import models

# Create your models here.

blowhorn/basket/models.py
from blowhorn.basket.abstract_models import (
    AbstractBasket, AbstractLine, AbstractLineAttribute)
from blowhorn.oscar.core.loading import is_model_registered

__all__ = [
    'InvalidBasketLineError',
]


class InvalidBasketLineError(Exception):
    pass


if not is_model_registered('basket', 'Basket'):
    class Basket(AbstractBasket):
        pass

    __all__.append('Basket')


if not is_model_registered('basket', 'Line'):
    class Line(AbstractLine):
        pass

    __all__.append('Line')


if not is_model_registered('basket', 'LineAttribute'):
    class LineAttribute(AbstractLineAttribute):
        pass

    __all__.append('LineAttribute')

blowhorn/templates/organizations/login.html
{% extends "organizations_base.html" %}
{% block content %}
  <h1 id="login-header">Log in to your dashboard</h1>
  <div id="login-box">
    <form method="post" action="{% url login %}">{% csrf_token %}
        {{ form }}
        <input type="submit" value="Login">
    </form>
    <p>Forgotten your password? <a href="{% url "password_reset" %}">Reset it.</a></p>
  </div>
{% endblock %}

blowhorn/templates/organizations/organization_confirm_delete.html
{% extends "organizations_base.html" %}
{% block content %}
<h1>{{ organization }}</h1>
<h3>Are you sure you want to delete this organization?</h3>
<form action="." method="post">{% csrf_token %}
    {{ form }}
    <input type="submit" value="Delete">
</form>
{% endblock %}

blowhorn/templates/organizations/organization_detail.html
{% extends "organizations_base.html" %}
{% load org_tags %}
{% block content %}
<h1>{{ organization }}</h1>
<ul>
    <li><a href="{% url "organization_edit" organization.pk %}">Edit</a></li>
    <li><a href="{% url "organization_delete" organization.pk %}">Delete</a></li>
    <li><a href="{% url "organization_user_add" organization.pk %}">Add a member</a></li>
</ul>
{% organization_users organization %}
{% endblock %}

blowhorn/templates/organizations/organization_form.html
{% extends "organizations_base.html" %}
{% block content %}
<h1>{{ organization }}</h1>
<form action="." method="post">{% csrf_token %}
    {{ form }}
    <input type="submit" value="submit">
</form>
{% endblock %}

blowhorn/templates/organizations/organization_list.html
{% extends "organizations_base.html" %}
{% block content %}
<h1>organizations</h1>

<ul>
    {% for organization in organizations %}
    <li><a href="{{ organization.get_absolute_url }}">{{ organization }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

blowhorn/templates/organizations/organization_users.html
<ul>
    {% for organization_user in organization_users %}
    <li>
    <a href="{{ organization_user.get_absolute_url }}">{{ organization_user }}</a>
    {% if not organization_user.user.is_active %}Send reminder{% endif %}
    </li>
    {% endfor %}
</ul>

blowhorn/templates/organizations/organizationuser_confirm_delete.html
{% extends "organizations_base.html" %}
{% block content %}
<h1>{{ organization }}</h1>
<form action="." method="post">{% csrf_token %}
    {{ form }}
    <input type="submit" value="Delete">
</form>
{% endblock %}

blowhorn/templates/organizations/organizationuser_detail.html
{% extends "organizations_base.html" %}
{% block content %}
<h1> {{ organization_user }} @ {{ organization }}</h1>
{% if user == organization_user.user %}This is you!{% endif %}
<ul>
    <li>Name: {{ organization_user.full_name }}</li>
    <li>Email: {{ organization_user.user.email }}</li>
</ul>
<ul>
    <li><a href="{% url "organization_user_edit" organization.pk organization_user.user.pk %}">Edit</a></li>
    <li><a href="{% url "organization_user_delete" organization.pk organization_user.user.pk %}">Delete</a></li>
</ul>
{% endblock %}

blowhorn/templates/organizations/organizationuser_form.html
{% extends "organizations_base.html" %}
{% block content %}
{% if profile %}
<h1>Update your profile</h1>
{% else %}
<h1> {{ organization_user }} @ {{ organization }}</h1>
{% endif %}
{% if user == organization_user.user %}This is you!{% endif %}
<form action="." method="post">{% csrf_token %}
    {{ form }}
    <input type="submit" value="submit">
</form>
{% endblock %}

blowhorn/templates/organizations/organizationuser_list.html
{% extends "organizations_base.html" %}
{% load org_tags %}
{% block content %}
<h1>{{ organization }}'s Members</h1>
<ul>
    <li><a href="{% url "organization_user_add" organization.pk %}">Add a member</a></li>
</ul>
{% organization_users organization %}
{% endblock %}

blowhorn/templates/organizations/organizationuser_remind.html
{% extends "organizations_base.html" %}
{% block content %}
<h1>{{ organization }}</h1>
<form action="." method="post">{% csrf_token %}
    {{ form }}
    <input type="submit" value="Send reminder">
</form>
{% endblock %}

blowhorn/templates/organizations/register_form.html
{% load static i18n %}
<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
<link href="{% static 'website/css/font-awesome.min.css' %}" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/invitation.css' %}">
<link href="https://fonts.googleapis.com/css?family=Heebo:100,300,400,500,700,800,900" rel="stylesheet">
<head>
  <title>Blowhorn - Intracity Logistics for Same-Day Delivery</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
  <meta data-hid="description" name="description" content="From Micro-warehousing to Hyperlocal Distribution, we provide same-day delivery for a variety of intracity logistics needs">
  <meta name="keywords" content="logistics solutions, logistics Services, end to end logistics">
  <meta property="og:title" name="og:title" content="Blowhorn - Blowhorn | Intracity Logistics for Same-Day Delivery">
  <meta property="og:type" name="og:type" content="website">
  <meta property="og:url" name="og:url" content="https://blowhorn.com/">
  <meta property="og:image" name="og:image" content="https://docs.blowhorn.com/social_banner_a8cef740c4.png">
  <meta property="og:description" name="og:description" content="From Micro-warehousing to Hyperlocal Distribution, we provide same-day delivery for a variety of intracity logistics needs">
  <meta property="og:locale" name="og:locale" content="en_IN">
  <meta property="og:locale:alternate" name="og:locale:alternate" content="en_US">
  <meta property="og:site_name" name="og:site_name" content="blowhorn">
  <meta property="google-signin-client_id" name="google-signin-client_id" content="309303081199-mfh2l774kgcfs49a37qne030nj7sf9iu.apps.googleusercontent.com">
  <meta property="google-signin-scope" name="google-signin-scope" content="https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/userinfo.email">
  <meta property="google-signin-requestvisibleactions" name="google-signin-requestvisibleactions" content="https://schemas.google.com/AddActivity">
  <meta property="google-signin-cookiepolicy" name="google-signin-cookiepolicy" content="single_host_origin">
  <meta property="facebook-app-id" name="facebook-app-id" content="120045861414801">
  <meta property="fb:app_id" content="120045861414801">
  <meta data-hid="mobile-web-app-capable" name="mobile-web-app-capable" content="yes">
  <meta data-hid="apple-mobile-web-app-title" name="apple-mobile-web-app-title" content="blowhorn">
  <link rel="icon" type="image/x-icon" href="/static/assets/images/favicon.ico">
  <link rel="shortcut icon" href="/static/assets/images/favicon-32x32.png">
  <!-- Global Site Tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-52796945-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-52796945-1');
  </script>
</head>
<main>
  <div class="relative overflow-hidden p-6 min-h-screen" style="background-image: url('https://docs.blowhorn.com/truck_1_cb410e2131.jpg')">
    <div class="absolute mask w-full top-0 left-0 z-10"></div>
    <div class="container mx-auto relative max-w-7xl">
      <div class="flex flex-col md:flex-row items-center justify-center md:justify-start pt-32 pb-16 md:pb-0">
        <div class="w-full px-8 z-20 bg-white mx-auto max-w-xs md:max-w-md p-6 shadow-lg rounded-lg overflow-hidden">
          <div class="flex flex-col justify-center items-center">
            <a href="/">
              <img src="/static/website/images/blowhorn/logo/logoDark2X.png" alt="logo" class="logo w-16">
            </a>
            <div class="text-blue-900">Welcome to Blowhorn</div>
          </div>
          <div class="flex flex-col mx-auto">
            <div class="modal-header">
              <h1 class="text-2xl font-bold text-center mb-4 text-gray-700">
                {% trans "Registration Form" %}
              </h1>
            </div>
            <form action="." method="post" class="flex flex-col">
              {% csrf_token %}
              {{ form }}
              <div class="flex justify-center items-center mt-4">
                <input type="submit" value="Submit" class="w-full py-4 px-8 rounded-lg font-bold mx-auto bg-gradient-to-r from-blue-500 to-purple-500 text-white flex items-center justify-center cursor-pointer" type="button" title="submit" name="action">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
<script type="application/javascript">
  (function ($) {
    $(document).ready(() => {
      $('#id_name, #id_email, #id_phone_number_1, #id_password, #id_password_confirm, #id_phone_number_0').addClass('block text-sm py-3 px-4 rounded-lg w-full border outline-none');
      $('#id_email').prop('readonly', 'readonly').addClass('bg-gray-400');
      $('#id_password').prop('placeholder', 'Password');
      $('#id_password_confirm').prop('placeholder', 'Confirm Password');
      $('#id_phone_number_1').addClass('mt-1')
      if ($('#id_phone_number_1').val()) {
        $('#id_phone_number_1').prop('readonly', 'readonly');
        $('#id_phone_number_1').addClass('mt-1');
      }
      $('#id_phone_number_0').find('option').prop('hidden', true);
      $('#id_phone_number_0').prop('readonly', 'readonly');
      $('label').addClass('text-gray-700 mt-2');
      $('#id_phone_number_1').keypress(function (e) {
        var charCode = (e.which) ? e.which : event.keyCode
        if (String.fromCharCode(charCode).match(/[^0-9]/g) || e.target.value.toString().length > 9) {
          return false;
        }
      });
    });
  })(jQuery);
</script>